### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by henriquesigned** [horizon-ui/horizon-tailwind-react-nextjs#1]
Anyone having the same issue?

> horizon-tailwind-react-nextjs@1.0.0 dev
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
warning package.json: "dependencies" has dependency "@types/node" with range "^12.20.55" that collides with a dependency in "devDependencies" of the same name with version "^18.7.6"
warning package.json: "dependencies" has dependency "@types/react" with range "^18.0.15" that collides with a dependency in "devDependencies" of the same name with version "18.2.0"
warning package.json: "dependencies" has dependency "@types/react-dom" with range "^18.0.6" that collides with a dependency in "devDependencies" of the same name with version "^18.2.1"
(node:93919) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ▲ Next.js 13.5.5
  - Local:        http://localhost:3001
  - Experiments (use at your own risk):
     · appDir

 ✓ Ready in 2.5s
 ✓ Compiled /page in 2.5s (511 modules)
 ⨯ TypeError: e.getSetCookie is not a function
    at Home (./src/app/page.tsx:9:62)
    at stringify (<anonymous>)
 ✓ Compiled in 241ms (259 modules)

**Comment by simmmpleweb** [comment]
Hello, @henriquesigned ! I fixed the error and everything should be fine !
Regards, Vlad.
