### ISSUE TITLE
Rtl can not be activated.

### ISSUE THREAD

**Issue by peterjidamva** [horizon-ui/horizon-tailwind-react-nextjs#4]

**Comment by simmmpleweb** [comment]
Hello, @peterjidamva ! For us to solve the issue we need more info about the problem, otherwise I will have to close the issue.

**Comment by peterjidamva** [comment]
a toggle switch that shift from normal to rtl would be good. I could not find that

**Comment by simmmpleweb** [comment]
We do not have this functionality, however, we offer an RTL page with an RTL layout which you can build on top of!
Regards, Vlad.
