### ISSUE TITLE
[UI Bug] Sign-in page white space 

### ISSUE THREAD

**Issue by mananpatel06** [horizon-ui/horizon-tailwind-react-nextjs#8]
### Bug details:-
White space at the end of Sign-in page.

For large-screen devices, website height is screen height, and that is the reason behind the bug.

### Issue Recording 👇

https://github.com/user-attachments/assets/6011481d-5fa1-4410-bcdb-5120415760e3

**Comment by mananpatel06** [comment]
Fixed similar issue on [horizon-tailwind-react](https://github.com/horizon-ui/horizon-tailwind-react)

[Pull Request Link](https://github.com/horizon-ui/horizon-tailwind-react/pull/11)

**Comment by simmmpleweb** [comment]
Fixed with [PR](https://github.com/horizon-ui/horizon-tailwind-react-nextjs/pull/9)
